import fs from 'node:fs';import path from 'node:path';import * as T from '../dist/vendor/three.module.js';import {createCampus} from '../dist/campus.js';import {createStudent} from '../dist/student.js';import {createFilmProps} from '../dist/film-props.js';import {evaluateFilm,applyFilmFrame} from '../dist/film-director.js';import {SHOTS} from '../dist/film-sequences.js';
const out=process.argv[2],full=process.argv.includes('--full');fs.mkdirSync(out,{recursive:true});globalThis.ProgressEvent=class{constructor(t,v){Object.assign(this,v)}};
const campus=createCampus(),scene=new T.Group();scene.add(campus.group,createFilmProps());const backdrop=new T.Mesh(new T.PlaneGeometry(12000,12000),new T.MeshStandardMaterial({color:'#d7e3d9'}));backdrop.rotation.x=-Math.PI/2;backdrop.position.y=-45;scene.add(backdrop);scene.updateMatrixWorld(true);
function geometry(root,skin=false){const v=[],ix=[],p=new T.Vector3(),n=new T.Vector3(),nm=new T.Matrix3();root.updateMatrixWorld(true);function add(o,w){const g=o.geometry,a=g.attributes.position,b=g.attributes.normal,base=v.length/9;nm.getNormalMatrix(w);for(let i=0;i<a.count;i++){if(skin&&o.isSkinnedMesh)o.getVertexPosition(i,p);else p.fromBufferAttribute(a,i);p.applyMatrix4(w);n.fromBufferAttribute(b,i).applyNormalMatrix(nm);v.push(...p,...n,o.material.color.r,o.material.color.g,o.material.color.b);}if(g.index)for(const i of g.index.array)ix.push(base+i);else for(let i=0;i<a.count;i++)ix.push(base+i);}
 root.traverseVisible(o=>{if(!o.isMesh)return;if(o.isInstancedMesh){const m=new T.Matrix4(),w=new T.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,m);add(o,w.multiplyMatrices(o.matrixWorld,m));}}else add(o,o.matrixWorld);});return {v:new Float32Array(v),i:new Uint32Array(ix)};}
function writeAll(fd,buffer,position){let at=0;while(at<buffer.length){const n=fs.writeSync(fd,buffer,at,Math.min(1024*1024,buffer.length-at),position+at);if(n<=0)throw Error('Incomplete geometry write');at+=n;}}
function writeComplete(file,buffer){const tmp=file+'.partial',fd=fs.openSync(tmp,'w');writeAll(fd,buffer,0);fs.closeSync(fd);if(fs.statSync(tmp).size!==buffer.length)throw Error('Mesh size mismatch: '+file);fs.renameSync(tmp,file);}
const staticMesh=geometry(scene);writeComplete(path.join(out,'static.v'),Buffer.from(staticMesh.v.buffer));writeComplete(path.join(out,'static.i'),Buffer.from(staticMesh.i.buffer));
const b=fs.readFileSync(new URL('../dist/assets/student.glb',import.meta.url)),student=createStudent({data:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)});await student.ready;if(!student.loaded)throw student.error;
const customTimes=process.argv.find(a=>a.startsWith('--times='))?.slice(8).split(',').map(Number);
const cam=new T.PerspectiveCamera(39,16/9,.1,2800),times=customTimes||(full?Array.from({length:2700},(_,i)=>i/30):SHOTS.flatMap(s=>[s.startTime+.15,s.startTime+s.duration*.5,s.startTime+s.duration-.1])),frames=[];
const dynamicPath=path.join(out,'actors.bin.partial'),dynamic=fs.openSync(dynamicPath,'w');let offset=0,collisions=[];
for(let j=0;j<times.length;j++){
 const f=evaluateFilm(times[j],campus);applyFilmFrame(f,cam,student);let actor=null;
 if(f.actor){if(!f.shot.character.stepDown&&campus.blocked(f.actor.position[0],f.actor.position[2],.22))collisions.push({time:f.time,id:f.shot.id,position:f.actor.position});const g=geometry(student.group,true);const vb=Buffer.from(g.v.buffer),ib=Buffer.from(g.i.buffer);writeAll(dynamic,vb,offset);writeAll(dynamic,ib,offset+vb.length);actor={offset,vbytes:vb.length,ibytes:ib.length};offset+=vb.length+ib.length;}
 frames.push({time:f.time,id:f.shot.id,position:f.position,target:f.target,actor,actorPosition:f.actor?.position,vp:new T.Matrix4().multiplyMatrices(cam.projectionMatrix,cam.matrixWorldInverse).elements,caption:f.caption,captionOpacity:f.captionOpacity,photo:f.photo,photoProgress:f.photoProgress,flash:f.flash,fade:f.fade});
 if(j%300===0)console.log('frame',j,'/',times.length);
}
fs.closeSync(dynamic);if(fs.statSync(dynamicPath).size!==offset)throw Error('Actor bytes incomplete');fs.renameSync(dynamicPath,path.join(out,'actors.bin'));fs.writeFileSync(path.join(out,'frames.json'),JSON.stringify(frames));fs.writeFileSync(path.join(out,'collisions.json'),JSON.stringify(collisions));console.log(JSON.stringify({staticVertices:staticMesh.v.length/9,frames:frames.length,collisions:collisions.length,actorBytes:offset}));
